import fs from 'node:fs';
import path from 'node:path';
import jsesc from 'jsesc';

const DATA_DIR = path.resolve(import.meta.dirname, '../data');
const SRC_DIR = path.resolve(import.meta.dirname, '../src');

async function main() {
	if (!fs.existsSync(path.join(DATA_DIR, 'entities.json'))) {
		console.log('entities.json not found. Fetching...');
		const response = await fetch('https://html.spec.whatwg.org/entities.json');
		const json = await response.text();
		fs.writeFileSync(path.join(DATA_DIR, 'entities.json'), json.replace(/  /g, '\t') + '\n');
	}

	console.log('Scraping HTML spec...');
	const { execSync } = await import('node:child_process');
	
	execSync('bun scripts/scrape-spec.ts', { stdio: 'inherit' });
	execSync('bun scripts/process-data.ts', { stdio: 'inherit' });

	console.log('Generating src/data.ts...');
	
	const decodeMap = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'decode-map.json'), 'utf8'));
	const decodeMapLegacy = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'decode-map-legacy.json'), 'utf8'));
	const decodeMapOverrides = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'decode-map-overrides.json'), 'utf8'));
	const invalidCodePointsList = JSON.parse(fs.readFileSync(path.join(DATA_DIR, 'invalid-character-reference-code-points.json'), 'utf8'));

	const regexAstralSymbol = /[\uD800-\uDBFF][\uDC00-\uDFFF]/g;
	const regexAsciiWhitelist = /[\x01-\x21\x23-\x26\x28-\x3C\x3E-\x7E]/g;
	const regexBmpWhitelist = /[\x01-\x08\x0B\x0C\x0E-\x1F\x7F-\x84\x86-\x9F\uFDD0-\uFDEF\uFFFE\uFFFF]|[\uD83F\uD87F\uD8BF\uD8FF\uDA3F\uDA7F\uDABF\uDAFF\uDB3F\uDB7F\uDBBF\uDBFF][\uDFFE\uDFFF]/g;
	const regexEncodeNonAscii = /[\uD83F\uD87F\uD8BF\uD8FF\uDA3F\uDA7F\uDABF\uDAFF\uDB3F\uDB7F\uDBBF\uDBFF][\uDFFE\uDFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]|[^\x20-\x21\x23-\x25\x28-\x3B\x3D\x3F-\x5F\x61-\x7E]/g;
	const regexInvalidRawCodePoints = /[\x00-\x08\x0B\x0E-\x1F\x7F-\x9F\uFDD0-\uFDEF\uFFFE\uFFFF]|[\uD83F\uD87F\uD8BF\uD8FF\uDA3F\uDA7F\uDABF\uDAFF\uDB3F\uDB7F\uDBBF\uDBFF][\uDFFE\uDFFF]|[\uD800-\uDBFF][\uDC00-\uDFFF]/;

	const packMap = (map: Record<string, string>) => {
		return Object.entries(map).map(([k, v]) => `${k}\x01${v}`).join('\x02');
	};

	const dataContent = `/**
 * This file is auto-generated by scripts/generate-data.ts
 * Do not edit manually.
 */

export const version = '${JSON.parse(fs.readFileSync('package.json', 'utf8')).version}';

// Packed data format: "key1\x01val1\x02key2\x01val2..."
export const decodeData = ${jsesc(packMap(decodeMap), { quotes: 'single', wrap: true })};
export const decodeDataLegacy = ${jsesc(packMap(decodeMapLegacy), { quotes: 'single', wrap: true })};
export const decodeDataOverrides = ${jsesc(packMap(decodeMapOverrides), { quotes: 'single', wrap: true })};
export const invalidCodePoints = '${invalidCodePointsList.join(',')}';

export const regexAstralSymbol = ${regexAstralSymbol.toString()};
export const regexAsciiWhitelist = ${regexAsciiWhitelist.toString()};
export const regexBmpWhitelist = ${regexBmpWhitelist.toString()};
export const regexEncodeNonAscii = ${regexEncodeNonAscii.toString()};

export const regexDecimalEscapeSource = '&#([0-9]+)(;?)';
export const regexHexadecimalEscapeSource = '&#[xX]([a-fA-F0-9]+)(;?)';
export const regexAmbiguousAmpersandSource = '&([0-9a-zA-Z]+)';
export const regexInvalidRawCodePoints = ${regexInvalidRawCodePoints.toString()};
`;

	fs.writeFileSync(path.join(SRC_DIR, 'data.ts'), dataContent.trim() + '\n');
	console.log('src/data.ts generated successfully.');
}

main().catch(console.error);
